/**
 * ADR Generator
 * 
 * Generates Architecture Decision Record files.
 */

import type { GenerationContext } from './types';

interface ADRManifest {
  adr: Array<{
    id: string;
    name: string;
    file: string;
  }>;
}

/**
 * Generate all ADR files
 */
export function generate(context: GenerationContext & { manifest: ADRManifest }): { errors: string[] } {
  const errors: string[] = [];

  const { manifest } = context;

  for (const adr of manifest.adr) {
    const content = generateADRContent(adr.id, adr.name);

    const result = context.writeFile(adr.file, content);
    if (!result.success && result.error) {
      errors.push(result.error);
    }
  }

  return { errors };
}

/**
 * Generate ADR content
 */
function generateADRContent(id: string, name: string): string {
  const title = formatTitle(name);

  return `# ${id}: ${title}

**Status:** Proposed
**Date:** ${new Date().toISOString().split('T')[0]}
**Deciders:** Astro Engineering OS Team

## Context

[Describe the problem or situation that requires a decision]

### Decision Drivers

1. [Driver 1]
2. [Driver 2]
3. [Driver 3]

## Decision

[Describe the decided approach]

### Implementation

[How the decision will be implemented]

## Alternatives Considered

### Option 1: [Name]

**Description:** [Description]

**Pros:**
- [Pro 1]

**Cons:**
- [Con 1]

**Verdict:** [Accepted | Rejected | Deferred]

### Option 2: [Name]

**Description:** [Description]

**Pros:**
- [Pro 1]

**Cons:**
- [Con 1]

**Verdict:** [Accepted | Rejected | Deferred]

## Tradeoffs

### Positive Consequences

- [Positive consequence 1]
- [Positive consequence 2]

### Negative Consequences

- [Negative consequence 1]
- [Negative consequence 2]

### Neutral Consequences

- [Neutral consequence 1]

## Consequences

### Immediate

- [Immediate consequence 1]

### Short-term

- [Short-term consequence 1]

### Long-term

- [Long-term consequence 1]

## Future Considerations

### Revisit Triggers

1. [Trigger 1]

### Potential Extensions

1. [Extension 1]

## Related ADRs

- [ADR-XXX: Related Decision](./ADR-XXX-name.md)

## Notes

[Any additional notes]

---
*Generated by Astro Engineering OS Bootstrap Generator*
`;
}

/**
 * Format ADR name to title
 */
function formatTitle(name: string): string {
  return name
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

export const adr = { generate };