/**
 * Docs Generator
 * 
 * Generates documentation files.
 */

import type { GenerationContext } from './types';

interface DocsManifest {
  docs?: string[];
}

/**
 * Generate all documentation files
 */
export function generate(context: GenerationContext & { manifest: DocsManifest }): { errors: string[] } {
  const errors: string[] = [];

  // Generate main docs
  const mainDocs = [
    'getting-started.md',
    'architecture.md',
    'skills.md',
    'governance.md',
    'reviewers.md',
    'workflows.md',
    'agents.md',
    'orchestrator.md',
  ];

  for (const doc of mainDocs) {
    const content = generateDocContent(doc);
    const filePath = `docs/${doc}`;
    const result = context.writeFile(filePath, content);
    if (!result.success && result.error) {
      errors.push(result.error);
    }
  }

  return { errors };
}

/**
 * Generate documentation content
 */
function generateDocContent(doc: string): string {
  const title = formatTitle(doc.replace('.md', ''));

  return `# ${title}

${getDescription(doc)}

## Overview

This document provides guidance on ${doc.replace('.md', '')} in Astro Engineering OS.

## Contents

### Quick Reference

- [Key concept 1]
- [Key concept 2]
- [Key concept 3]

### Detailed Sections

#### Section 1

[Content for section 1]

#### Section 2

[Content for section 2]

### Examples

#### Example 1

\`\`\`typescript
// Example code
const example = 'example';
\`\`\`

## Related Documentation

- [Related doc 1](../path/to/doc1.md)
- [Related doc 2](../path/to/doc2.md)

## Further Reading

- [External resource 1](https://example.com)
- [External resource 2](https://example.com)

---
*Generated by Astro Engineering OS Bootstrap Generator*
`;
}

/**
 * Format doc name to title
 */
function formatTitle(name: string): string {
  return name
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Get description for doc
 */
function getDescription(doc: string): string {
  const descriptions: Record<string, string> = {
    'getting-started': 'A comprehensive guide to getting started with Astro Engineering OS.',
    'architecture': 'Deep dive into Astro Engineering OS architecture and design principles.',
    'skills': 'Learn how to use and create skills for specialized domains.',
    'governance': 'Standards and rules for Astro Engineering OS projects.',
    'reviewers': 'Automated review systems for quality assurance.',
    'workflows': 'Standardized engineering processes for common tasks.',
    'agents': 'AI agent system for Astro development.',
    'orchestrator': 'Central coordination layer for AI agents.',
  };

  return descriptions[doc] || `Documentation for ${doc.replace('.md', '')}.`;
}

export const docs = { generate };