/**
 * GitHub Generator
 * 
 * Generates GitHub template and workflow files.
 */

import type { GenerationContext } from './types';

interface GitHubManifest {
  github: {
    workflows: string[];
    templates: string[];
  };
}

/**
 * Generate all GitHub files
 */
export function generate(context: GenerationContext & { manifest: GitHubManifest }): { errors: string[] } {
  const errors: string[] = [];

  const { manifest } = context;

  // Generate workflows
  for (const workflow of manifest.github.workflows) {
    const content = generateWorkflowContent(workflow);
    const result = context.writeFile(workflow, content);
    if (!result.success && result.error) {
      errors.push(result.error);
    }
  }

  // Generate templates
  for (const template of manifest.github.templates) {
    const content = generateTemplateContent(template);
    const result = context.writeFile(template, content);
    if (!result.success && result.error) {
      errors.push(result.error);
    }
  }

  return { errors };
}

/**
 * Generate GitHub Actions workflow content
 */
function generateWorkflowContent(workflow: string): string {
  const name = workflow.split('/').pop()?.replace('.yml', '') || 'ci';

  if (name === 'ci') {
    return `# CI Workflow

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run test

---
*Generated by Astro Engineering OS Bootstrap Generator*
`;
  }

  if (name === 'release') {
    return `# Release Workflow

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

---
*Generated by Astro Engineering OS Bootstrap Generator*
`;
  }

  return `# ${name} workflow

---
*Generated by Astro Engineering OS Bootstrap Generator*
`;
}

/**
 * Generate issue/PR template content
 */
function generateTemplateContent(template: string): string {
  const name = template.split('/').pop()?.replace('.yml', '') || 'template';

  return `---
name: ${formatTemplateName(name)}
description: ${getTemplateDescription(name)}
title: '[${getPrefix(name)}] '
labels: ['triage']
---

## Description

[Describe the issue or PR]

## Type

- [ ] Bug fix
- [ ] New feature
- [ ] Documentation
- [ ] Refactoring

## Checklist

- [ ] I have searched for similar issues/PRs
- [ ] I have included all relevant information
- [ ] I am willing to help implement this

## Additional Context

[Any other relevant information]

---
*Generated by Astro Engineering OS Bootstrap Generator*
`;
}

/**
 * Format template name
 */
function formatTemplateName(name: string): string {
  return name
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Get template description
 */
function getTemplateDescription(name: string): string {
  const descriptions: Record<string, string> = {
    bug: 'Report a bug to help us improve',
    feature: 'Suggest an idea for this project',
    refactor: 'Suggest a code or architecture refactoring',
  };

  return descriptions[name] || 'Template for this repository';
}

/**
 * Get PR prefix
 */
function getPrefix(name: string): string {
  const prefixes: Record<string, string> = {
    bug: 'BUG',
    feature: 'FEATURE',
    refactor: 'REFACTOR',
    pr: 'PR',
  };

  return prefixes[name] || name.toUpperCase().slice(0, 3);
}

export const github = { generate };