/**
 * Governance Generator
 * 
 * Generates governance document files.
 */

import type { GenerationContext } from './types';

interface GovernanceManifest {
  governance: Array<{
    name: string;
    file: string;
  }>;
}

interface GenerateOptions {
  root: string;
  skipExisting: boolean;
}

/**
 * Generate all governance documents
 */
export function generate(context: GenerationContext & { manifest: GovernanceManifest }): { errors: string[] } {
  const errors: string[] = [];

  const { manifest } = context;

  for (const gov of manifest.governance) {
    const content = `# ${formatTitle(gov.name)} Governance

## Overview

This document defines ${gov.name} standards for Astro Engineering OS projects.

## Purpose

Establishes rules and patterns for ${gov.name} to ensure consistency and quality.

## Key Principles

### Core Rules

1. **Consistency** - Follow established patterns
2. **Maintainability** - Write code that can be understood and modified
3. **Performance** - Consider performance implications
4. **Accessibility** - Build inclusive experiences

## Standards

### Required

- [ ] All files must follow naming conventions
- [ ] Components must have explicit types
- [ ] Tests must cover critical paths
- [ ] Documentation must be updated

### Forbidden

- [ ] No \`any\` types without justification
- [ ] No default exports in TypeScript
- [ ] No inline styles (use classes)
- [ ] No console.log in production code

## Enforcement

### Automated

- ESLint for code style
- TypeScript strict mode
- Pre-commit hooks

### Manual

- Code review
- Architecture review
- Security review

## Related Documents

- [Architecture](../governance/architecture.md)
- [Components](../governance/components.md)
- [Dependencies](../governance/dependencies.md)

---
*Generated by Astro Engineering OS Bootstrap Generator*
`;

    const result = context.writeFile(gov.file, content);
    if (!result.success && result.error) {
      errors.push(result.error);
    }
  }

  return { errors };
}

/**
 * Format governance name to title
 */
function formatTitle(name: string): string {
  return name
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

export const governance = { generate };