/**
 * Reviewers Generator
 * 
 * Generates reviewer system files.
 */

import type { GenerationContext } from './types';

interface ReviewerManifest {
  reviewers: Array<{
    name: string;
    file: string;
  }>;
}

/**
 * Generate all reviewer files
 */
export function generate(context: GenerationContext & { manifest: ReviewerManifest }): { errors: string[] } {
  const errors: string[] = [];

  const { manifest } = context;

  for (const reviewer of manifest.reviewers) {
    const content = generateReviewerContent(reviewer.name);

    const result = context.writeFile(reviewer.file, content);
    if (!result.success && result.error) {
      errors.push(result.error);
    }
  }

  return { errors };
}

/**
 * Generate reviewer content
 */
function generateReviewerContent(name: string): string {
  const title = formatTitle(name);
  
  return `# ${title} Reviewer

Automated ${title.toLowerCase()} compliance checking for Astro projects.

## Review Objectives

### Primary Goals

1. **Compliance** - Ensure ${name} standards are met
2. **Quality** - Maintain high ${name.toLowerCase()} quality
3. **Consistency** - Apply ${name.toLowerCase()} standards uniformly

### Scope

This reviewer evaluates:

- ${name} implementation patterns
- ${name} anti-patterns
- ${name} best practices
- ${name} documentation

## Scoring System

### Score Interpretation

| Score | Grade | Description |
|-------|-------|-------------|
| 5 | Excellent | Exceeds standards |
| 4 | Good | Meets standards |
| 3 | Acceptable | Meets minimum |
| 2 | Poor | Below standards |
| 1 | Failing | Major violations |

### Category Scores

| Category | Weight | Score |
|----------|---------|-------|
| Pattern compliance | 30% | 1-5 |
| Anti-pattern detection | 25% | 1-5 |
| Best practice adherence | 25% | 1-5 |
| Documentation | 20% | 1-5 |

## Review Criteria

### Required Checks

1. **Pattern usage** - Are established patterns followed?
2. **Anti-pattern detection** - Are known issues avoided?
3. **Best practices** - Are recommendations implemented?
4. **Documentation** - Is ${name} properly documented?

### Severity Levels

| Level | Definition | Action |
|-------|------------|--------|
| Critical | Major violation | Immediate fix |
| High | Significant issue | Must fix |
| Medium | Moderate issue | Should fix |
| Low | Minor issue | Could fix |

## Rejection Criteria

### Automatic Rejection

- Score below 2 in any category
- Critical severity findings unresolved
- Major anti-patterns detected

### Conditional Rejection

- Score below 3 in any category
- Multiple High severity findings
- Missing documentation

## Findings Format

\`\`\`markdown
## ${title} Finding: [Title]

**Severity:** [Critical | High | Medium | Low]
**Category:** [Pattern | Anti-pattern | Practice | Documentation]

### Description

[What was found]

### Recommendation

[How to fix]

### Effort

[Low | Medium | High]
\`\`\`

## Improvement Strategies

### High Priority

1. Address critical findings
2. Fix high severity issues
3. Improve pattern compliance

### Medium Priority

1. Resolve medium findings
2. Add documentation
3. Improve best practices

### Low Priority

1. Polish remaining issues
2. Optimize existing code
3. Add examples

## Usage by AI Agents

### Architect Agent

Request ${name.toLowerCase()} review for:
- Design decisions
- Pattern selection
- Architecture proposals

### Implementer Agent

Request ${name.toLowerCase()} review after:
- Implementation
- Refactoring
- Pattern changes

---

*Generated by Astro Engineering OS Bootstrap Generator*
`;
}

/**
 * Format reviewer name to title
 */
function formatTitle(name: string): string {
  return name
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

export const reviewers = { generate };