/**
 * Skills Generator
 * 
 * Generates skill files from manifest definition.
 */

import type { GenerationContext } from './types';

interface SkillDefinition {
  name: string;
  file: string;
  description: string;
  modules?: string[];
  extends?: string;
  domain?: string;
}

interface SkillGenerator {
  name: string;
  file: string;
  modules: string[];
}

interface SkillsManifest {
  skills: {
    core: SkillDefinition;
    packs: SkillDefinition[];
  };
}

interface GenerateOptions {
  root: string;
  skipExisting: boolean;
}

/**
 * Generate all skill files
 */
export function generate(context: GenerationContext & { manifest: SkillsManifest }): { errors: string[] } {
  const errors: string[] = [];

  try {
    // Generate core skill
    generateCoreSkill(context);

    // Generate domain packs
    generateDomainPacks(context);
  } catch (error) {
    errors.push(`Skills generation failed: ${error}`);
  }

  return { errors };
}

/**
 * Generate core Astro skill
 */
function generateCoreSkill(context: GenerationContext & { manifest: SkillsManifest }): void {
  const { manifest } = context;
  const skill = manifest.skills.core;

  const content = `# ${skill.name}

${skill.description}

## Modules

${skill.modules?.map(m => `- ${m}`).join('\n') || ''}

## Overview

This is the foundational skill for Astro projects. It provides:

- Rendering strategies (SSG, SSR, Hybrid, Islands)
- Content management (Collections, MDX, Live Collections)
- Data handling (Actions, API Routes, Astro DB)
- Performance patterns (Hydration, Images, Fonts)
- Cloudflare integration (Workers, D1, R2, KV)

## Usage

Load this skill for any Astro project to ensure proper patterns and governance are applied.

---
*Generated by Astro Engineering OS Bootstrap Generator*
`;

  context.writeFile(skill.file, content);
}

/**
 * Generate domain pack skills
 */
function generateDomainPacks(context: GenerationContext & { manifest: SkillsManifest }): void {
  const { manifest } = context;

  for (const pack of manifest.skills.packs) {
    const content = `# ${pack.name} Pack

${pack.description || `Extends \`astro-core\` with patterns specific to ${pack.domain || pack.name} sites.`}

## Extends

This pack extends \`${pack.extends || 'astro-core'}\`.

## Modules

${pack.modules?.map(m => `- ${m}`).join('\n') || ''}

## Domain Focus

${pack.domain ? `This pack provides specialized knowledge for ${pack.domain} projects.` : ''}

## Prerequisites

- \`astro-core\` skill loaded
- Understanding of Astro rendering strategies
- Familiarity with the chosen rendering mode

## Usage

Load both \`astro-core\` and this domain pack for specialized ${pack.domain || pack.name} projects.

---
*Generated by Astro Engineering OS Bootstrap Generator*
`;

    context.writeFile(pack.file, content);
  }
}

export const skills = { generate };