/**
 * Workflows Generator
 * 
 * Generates workflow files.
 */

import type { GenerationContext } from './types';

interface WorkflowManifest {
  workflows: Array<{
    name: string;
    file: string;
  }>;
}

/**
 * Generate all workflow files
 */
export function generate(context: GenerationContext & { manifest: WorkflowManifest }): { errors: string[] } {
  const errors: string[] = [];

  const { manifest } = context;

  for (const workflow of manifest.workflows) {
    const content = generateWorkflowContent(workflow.name);

    const result = context.writeFile(workflow.file, content);
    if (!result.success && result.error) {
      errors.push(result.error);
    }
  }

  return { errors };
}

/**
 * Generate workflow content
 */
function generateWorkflowContent(name: string): string {
  const title = formatTitle(name.replace(/-/g, ' '));

  return `# ${title} Workflow

## Purpose

${getPurpose(name)}

## Inputs

### Required

- Feature description or requirements
- Acceptance criteria
- Project context

### Optional

- Design specifications
- Constraints
- Performance requirements

## Process

### Phase 1: Preparation

1. Review requirements
2. Assess scope
3. Gather context

### Phase 2: Analysis

1. Identify affected components
2. Assess complexity
3. Define success criteria

### Phase 3: Implementation

1. Execute changes
2. Write tests
3. Update documentation

### Phase 4: Review

1. Self-review
2. Agent review
3. Address feedback

### Phase 5: Completion

1. Verify all checks pass
2. Merge changes
3. Deploy if applicable

## Outputs

### Deliverables

- Implementation (code, tests)
- Documentation (README, API docs)
- Artifacts (logs, reports)

### Validation

- All tests pass
- All linting passes
- Documentation complete

## Success Criteria

| Criteria | Metric |
|----------|--------|
| Functionality | All acceptance criteria met |
| Quality | 0 errors, 0 warnings |
| Testing | 80%+ coverage |
| Documentation | Complete and accurate |

## Decision Points

### When to Stop?

| Condition | Action |
|-----------|--------|
| Requirements unclear | Pause, clarify |
| Technical blocker | Escalate |
| Scope creep | Reject additions |

### When to Pivot?

| Condition | Action |
|-----------|--------|
| Better solution found | Update approach |
| Requirements changed | Restart from Phase 1 |

## Anti-Patterns

### Avoid

- Skipping tests
- Ignoring review feedback
- Scope creep
- Premature optimization

### Signs to Stop

- Tests failing
- Reviewer rejections
- Quality below threshold

---

*Generated by Astro Engineering OS Bootstrap Generator*
`;
}

/**
 * Get workflow purpose
 */
function getPurpose(name: string): string {
  const purposes: Record<string, string> = {
    'feature-development': 'This workflow defines the process for developing new features, from concept through implementation and deployment.',
    'architecture-review': 'This workflow defines the process for reviewing architectural decisions and ensuring compliance with governance standards.',
    'migration': 'This workflow defines the process for migrating existing projects to Astro or upgrading between Astro versions.',
    'release': 'This workflow defines the process for releasing new versions, ensuring quality and traceability.',
    'refactoring': 'This workflow defines the process for refactoring existing code while maintaining functionality.',
  };

  return purposes[name] || `This workflow defines the ${name.replace(/-/g, ' ')} process.`;
}

/**
 * Format workflow name to title
 */
function formatTitle(name: string): string {
  return name
    .split(/[\s-]+/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

export const workflows = { generate };